trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - './terraform/*'    

pool:
  vmImage: 'ubuntu-latest'

variables:
- name: buildConfiguration
  value: 'Release'

- group: common

jobs:
- job: CI
  displayName: 'CI'
  steps:
    - task: UseDotNet@2
      displayName: 'Install .NET SDK'
      inputs:
        version: '6.0.x' # Use the version that matches your project

    
    - task: DotNetCoreCLI@2
      displayName: 'Restore NuGet packages'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Build the application'
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: 'Run unit tests'
      inputs:
        command: 'test'
        projects: '**/*Tests.csproj'
        arguments: '--configuration $(buildConfiguration) --collect:"XPlat Code Coverage"'

    - task: DotNetCoreCLI@2
      displayName: 'Publish the application'
      inputs:
        command: 'publish'
        projects: '**/*.csproj'
        publishWebProjects: true
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/publish'

    - task: PublishPipelineArtifact@1
      displayName: 'Publish artifacts'
      inputs:
        artifactName: 'publish'
        targetPath: '$(Build.ArtifactStagingDirectory)/publish'
    
- job: CD
  displayName: 'CD'
  dependsOn: CI
  pool:
    vmImage: 'windows-latest'
  variables:
  - group: env-dev
  steps:
    - task: UseDotNet@2
      displayName: 'Install .NET SDK'
      inputs:
        version: '6.0.x' # Use the version that matches your project

    - task: DownloadPipelineArtifact@2
      displayName: 'Download artifact'
      inputs:
        artifactName: 'publish'
        downloadPath: '$(System.ArtifactsDirectory)/publish'

    - task: AzureRmWebAppDeployment@4
      displayName: 'Deploy to Azure Web App'
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: '$(az_sc_name)'
        appType: 'webApp'
        WebAppName: '$(webapp1)'
        packageForLinux: '$(System.ArtifactsDirectory)/publish/**/*.zip'
        enableCustomDeployment: true
        DeploymentType: 'webDeploy'